package br.edu.utfpr.bacteria.ui;

import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

public class ImageFrame extends javax.swing.JInternalFrame {
    protected File imageFile;
    protected BufferedImage bufferedImage;

    public ImageFrame(File imageFile) throws Exception {
        this();
        this.imageFile = imageFile;
        this.bufferedImage = ImageIO.read(imageFile);
        setTitle(imageFile.getName());
        setSize(bufferedImage.getWidth(), bufferedImage.getHeight());
        jLabel.setIcon(new ImageIcon(bufferedImage));
    }

    /** Creates new form ImageFrame */
    private ImageFrame() {
        initComponents();
        setClosable(true);
    }

    public BufferedImage getBufferedImage() {
        return this.bufferedImage;
    }

    public File getImageFile() {
        return this.imageFile;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel = new javax.swing.JLabel();

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel;
    // End of variables declaration//GEN-END:variables

}
